/**
 * The client supplied this statement and asked for it to appear on the site
 * EXACTLY as written, without grammar or spelling corrections. Do not edit the
 * wording of this constant. It is used as the fallback when the admin has not
 * overridden `healer_message` in Site Settings.
 */
export const HEALER_MESSAGE =
  "GREETINGS TO YOU ALL MY GRANDCHILDREN: IT'S ME DR SALONGO HAMUZA A PROFESSIONAL TRANDITIONAL HEALER FROM UGANDA, I CATCTH THIEVES, MENTAL PROBLEMS, DABTES, IF YOU WANT POWER IN YOUR CHURCH, PROMOTION IN BUSINESSES, PROMOTION OF UPCOMING MUSICIANS, PROMOTION IN POLICE OR AMRY RANKS, RELATIONSHIP ISSUES, FAMILY ISSUES, TRAVEL QUICKER, YOU WANT TO CONCEIVE, CHILDREN WHO FAIL IN CLASSES, FISHER MEN , GETTING FINANCIAL LUCKS AND MANY OTHER ISSUES YOU CAN NAME. FOR MORE INFORMATION YOU CAN CONTACT ME ON: 0777172119";
